### ISSUE TITLE
Coffee Supplychain prototype needs an architecture + requirements

### ISSUE THREAD

**Issue by truedat101** [IoTone/substrate-coffee-supplychain#1]
![image](https://user-images.githubusercontent.com/64202/143393161-7b40484f-6d5a-4445-a711-7a1a153bd8e0.png)

## Overview 
Here are follow ups on the concept:

My goal is to create a simple coffee "supply chain" example that shows the harvest -> retail progression of the beans.  The asset tracking + chain of custody app would use an NFC tag to encode the data into the blockchain, with different scans of the tag carrying out actions related to the asset:

- harvest a batch (a tag for a big bag gets created)
- roast a batch
- bag the batch (at this point probably up to N new tags get created)
- bag(s) sent to warehouse
- bag(s) sent to distributor(s)
- bag(s) sold to retailer
- bag(s) purchased by customer
- verify chain of custody performed

At any point in the process someone can scan a tag and get the chain of custody and track the asset, just by scanning the tag.  This all lives on the blockchain  (in the box that I supply for now).  It could be on the greater world's blockchains, but actually the goal is to run it on a private blockchain that doesn't have fees associated with it for now, and supply chain members would run nodes as participants.

## Architecture

In terms of architecture, I think we need the following high level concepts as modifications to the original enterprise sample:

- Raw materials (i.e. unroasted beans,  roasted beans)
- coffee products (i.e. bagged, roasted, ground/whole beans, labeled for sale to market)
- Supply Chain Transactions (i.e. anything that happens between producers of beans, harvesting, to roasting, to distribution to retail)
- Retail Transactions (i.e. transactions from B2C sales)

We will likely need:

- A Retail Transaction Pallet (new)
- A Supply Chain Transaction Pallet (modification of Product Tracking Pallet)
- A Raw Materials Pallet (modification of Product Registry Pallet)
- A Coffee Products pallet (modification of Product Registry Pallet)

**Comment by truedat101** [comment]
Initial design can start without NFC.  The NFC work needs to be prototyped on #2  and can be integrated in a new issue.

**Comment by truedat101** [comment]
Design has been posted here: https://github.com/IoTone/BlockchainInABox/wiki/Blockchain-In-A-Box-for-supply-chain-asset-tracking-and-chain-of-custody-with-NFC---polkadot-substrate-as-a-private-blockchain.

Marking as done.

**Comment by Damfortx8** [comment]
@truedat101  I have a question regarding the connection between packing, transport and roasting, is it necessary to pack before roasting ? And the transport is because the place where it get roasted is different from where it is harvested?

**Comment by truedat101** [comment]
I would suggest that we can do the following, and I'll update the spec accordingly:

- beans are always harvested.  You can't skip harvesting
- processing is optional (I believe this step can be skipped since processing is a step that is often just skipped and they go with "natural" process)
- packing is optional  (some beans go straight from processing or harvesting into roasting without being packed and sold / distributed)
- Transport is an optional step that can go anywhere in between each step (for example, you could harvest, transport, process, transport, package, transport, roast, transport, package for retail, transport).  Part of the goal here is to start to give the consumer (and the manufacturer / brand) an idea of the carbon footprint of the beans.
