### ISSUE TITLE
Last details

### ISSUE THREAD

**Issue by Damfortx8** [IoTone/substrate-coffee-supplychain#9]
- verify unique sku
- clean fields when submit a transaction
- fix roasted enum error
- add question button
- add tracking to all steps?
- change event color depending of kind

**Comment by truedat101** [comment]
I've updated the spec to v4: https://github.com/IoTone/BlockchainInABox/wiki/Technical-Note-2---Blockchain-In-A-Box-for-supply-chain-asset-tracking-and-chain-of-custody-with-NFC---polkadot-substrate-as-a-private-blockchain.

Some modifications:

- added items 19-22

Noting: Item 11: t any point in the process someone can scan a tag and get the chain of custody and track the asset, just by scanning the tag. This all lives on the blockchain.

explains that we should be able to perform the verification step at any point in the process.  Chain of custody means that for any step in the process you can trace the product all the way back to its harvesting phase.  See the updated spec for a reference to the definition of chain of custody.
